package com.adn.adnapp.core.constants

object FirestoreKeys {
    const val USERS = "users"
    const val AREAS = "areas"
    const val NUTRITION = "nutrition"
    const val DAILY_CONSUMPTION = "dailyConsumption"
    const val INGESTED_FOODS = "ingestedFoods"
    const val NAME = "name"
    const val AGE = "age"
    const val WEIGHT = "weight"
    const val HEIGHT = "height"
    const val GENDER = "gender"
    const val DIETS = "diet"
    const val CUSTOM_DIETS = "customDiets"
    const val DESCRIPTION = "description"
    const val IMAGE_URL = "imageUrl"
    const val DIET_ID = "dietId"
    const val ONBOARDING_COMPLETED = "onboardingCompleted"
    const val CALORIES = "calories"
    const val PROTEINS = "proteins"
    const val CARBS = "carbs"
    const val FATS = "fats"
    const val SUGAR = "sugar"
    const val WATER_ML = "waterMl"
    const val PRODUCT_ID = "productId"
    const val QUANTITY = "quantity"
    const val KIND = "kind"
    const val TIMESTAMP = "timestamp"
    const val TARGET_WEIGHT = "targetWeight"
    const val BODY_GOAL = "bodyGoal"
    const val NUTRITION_IMPORTANCE = "nutritionImportance"
    const val SPORTS_IMPORTANCE = "sportsImportance"
    const val GOALS_IMPORTANCE = "goalsImportance"
    const val PRIORITIES_COMPLETED = "prioritiesCompleted"
    const val WEIGHT_HISTORY = "weightHistory"
    const val VALUE = "value"
    const val DATE = "date"
}
